### ISSUE TITLE
关于nmap -sn

### ISSUE THREAD

**Issue by lazypip** [busizhiya/Let-us-play-box#1]
namp -sn 扫描局域网段时会使用arp扫描，目标为公网ip或公网子网时才会使用icmp扫描
From Week4

**Comment by busizhiya** [comment]
感谢您的回复.
Nmap在man手册中的表述为:”-sn: Ping Scan - disable port scan“.
此处表述确实不严谨,但是强调的内容是后半句:”禁用端口扫描“.
感谢您的意见,我会在文中对此表述进行修改.
